### ISSUE TITLE
[iOS Designer Bootcamp] Assignment 3 Ready For Review

### ISSUE THREAD

**Issue by daneden** [daneden/Mailbox-Prototype#1]
The Mailbox Prototype assignment is complete & awaiting review. /cc @thecodepath

**Comment by timothy1ee** [comment]
Looks good! Instead of using state 0, 1, 2, 3, you can consider using enums so the code is more readable to you later.

**Comment by daneden** [comment]
@timothy1ee The nondescript case names did trip me up at one point. What would the syntax for enums be? Something like this?

``` swift
enum MessageState {
    case Archive, Delete, Reschedule, List
}

// Set this somewhere
var state = MessageState.Archive

switch state {
    case .Archive:
        // code

    case .Delete:
        // code

    case .Reschedule:
        // code

    case .List:
        // code

    default:
        // code
}
```

**Comment by timothy1ee** [comment]
Yep, that looks about right.
